<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Cohen_questionC.aspx.cs" Inherits="Cohen_Midterm2017.Cohen_questionC" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <style type="text/css">
        html
        {
            background-color:silver;
        }
        .content
        {
            padding:10px;
            background-color:white;
        }
        .movies
        {
            margin-bottom:20px;
        }
        .movies td,.movies th
        {
            padding:5px;
            border-bottom:solid 1px blue;
        }
        a
        {
            color:blue;
        }
    </style>
    <title>Movies</title>
</head>
<body>
    <form id="form1" runat="server">
    <div class ="content">

        <asp:GridView
        id="grdMovies"
        DataSourceID="Midterm"
        DataKeyNames="Id"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false"
        CssClass="movies" 
        GridLines="none"
        Runat="server">
        <Columns>
            <asp:BoundField
                DataField="Id"
                ReadOnly="true"
                HeaderText="Id" />
            <asp:BoundField
                DataField="Title"
                HeaderText="Title" />
        </Columns>
        </asp:GridView>

        <fieldset>
            <legend>Add Movie</legend>
            <asp:DetailsView
                id="dtlMovie"
                DataSourceID="Midterm"
                DefaultMode="Insert"
                AutoGenerateInsertButton="true"
                AutoGenerateRows="false"
                Runat="server">
                <Fields>
                    <asp:BoundField
                        DataField="Title"
                        HeaderText="Title:" />
                </Fields>
            </asp:DetailsView>
        </fieldset>
    
        <asp:ObjectDataSource
            id="Midterm"
            TypeName="Cohen_Midterm2017.Question_C.BusinessLogicLayer.Movie"
            SelectMethod="SelectAll"
            UpdateMethod="Update"
            InsertMethod="Insert"
            DeleteMethod="Delete"
            Runat="server" />

    </div>
    </form>
</body>
</html>
